# permissions for end users to edit imageplugins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: imageplugin-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-sample-operator
    app.kubernetes.io/part-of: k8s-sample-operator
    app.kubernetes.io/managed-by: kustomize
  name: imageplugin-editor-role
rules:
- apiGroups:
  - image.desiredcloud.com
  resources:
  - imageplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - image.desiredcloud.com
  resources:
  - imageplugins/status
  verbs:
  - get
